# Generated by Django 4.2.6 on 2023-11-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='services',
            field=models.ManyToManyField(through='services.Connection', to='services.service'),
        ),
    ]
