# Generated by Django 4.2.6 on 2023-11-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterias', '0001_initial'),
        ('pitches', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='criterias',
            field=models.ManyToManyField(through='criterias.MeetingCriteria', to='criterias.criteria'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='presentors',
            field=models.ManyToManyField(to='pitches.pitch'),
        ),
    ]
